version: '3.9'
name: 'fast_lms'

networks:
  dev:

x-base-project: &base-project
  env_file:
    - ./.env
  volumes:
    - ./:/opt/project
  build:
    context: .
    dockerfile: Dockerfile
    target: local

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - project
      - postgres-db
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './ssl-certificate/:/etc/letsencrypt/live/'
      - static_volume:/static
    networks:
      - dev

  project:
    <<: *base-project
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4", "--reload"]
    depends_on:
      - postgres-db
    ports:
      - "8000:8000"
    networks:
      - dev

  postgres-db:
    env_file:
      - ./.env
    image: postgres:15.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    networks:
      - dev

volumes:
  static_volume:
  pg_data: {}
